### ISSUE TITLE
trying to use branch and price algorithm using pyscipopt with python(anaconda)

### ISSUE THREAD

**Issue by Shobhitp2018** [scipopt/PySCIPOpt#381]

**Comment by Shobhitp2018** [comment]
1) i have installed anaconda
2) i  think i have installed scip ....(i.e. i have downloaded scip 7.0 and unpacked it and a folder is created in  C:\Program Files\SCIPOptSuite 6.0.2 ).
3)i have installed python 3.8
4)after giving the command pip install pyscipopt recieved the following text in cmd
C:\Users\Shobhit>pip install Pyscipopt
Collecting Pyscipopt
  Downloading https://files.pythonhosted.org/packages/ed/66/6904b21927f39d5dba3e9a0474bb246ff3fc11b3500292c4291942a92714/PySCIPOpt-3.0.0-cp38-cp38-win_amd64.whl (657kB)
     |████████████████████████████████| 665kB 192kB/s
Installing collected packages: Pyscipopt
Successfully installed Pyscipopt-3.0.0

**Comment by Shobhitp2018** [comment]
please guide me about the further steps .
i want to use scip and do the coding in spyder or jupyter to solve my optimization problem

**Comment by fserra** [comment]
I don't know what you are asking. What is the problem? Did you manage to install? If not, you might want to have a look at http://www.pokutta.com/blog/pages/scip/scip-teaching.html

An example of how to build and solve a model you find at
https://github.com/SCIP-Interfaces/PySCIPOpt#building-and-solving-a-model

**Comment by Shobhitp2018** [comment]
sorry about the confusion....
scip is installed but when i am using import pyscipopt in spyder it is giving this error
Traceback (most recent call last):
File "C:\Users\Shobhit\Anaconda3\envs\py38\lib\runpy.py", line 194, in _run_module_as_main
return _run_code(code, main_globals, None,
File "C:\Users\Shobhit\Anaconda3\envs\py38\lib\runpy.py", line 87, in _run_code
exec(code, run_globals)
File "C:\Users\Shobhit\Anaconda3\envs\py38\lib\site‑packages\spyder_kernels\console\__main__.py", line 11, in 
start.main()
File "C:\Users\Shobhit\Anaconda3\envs\py38\lib\site‑packages\spyder_kernels\console\start.py", line 297, in main
from ipykernel.kernelapp import IPKernelApp
File "C:\Users\Shobhit\Anaconda3\envs\py38\lib\site‑packages\ipykernel\__init__.py", line 2, in 
from .connect import *
File "C:\Users\Shobhit\Anaconda3\envs\py38\lib\site‑packages\ipykernel\connect.py", line 18, in 
import jupyter_client
File "C:\Users\Shobhit\Anaconda3\envs\py38\lib\site‑packages\jupyter_client\__init__.py", line 4, in 
from .connect import *
File "C:\Users\Shobhit\Anaconda3\envs\py38\lib\site‑packages\jupyter_client\connect.py", line 21, in 
import zmq
File "C:\Users\Shobhit\Anaconda3\envs\py38\lib\site‑packages\zmq\__init__.py", line 47, in 
from zmq import backend
File "C:\Users\Shobhit\Anaconda3\envs\py38\lib\site‑packages\zmq\backend\__init__.py", line 40, in 
reraise(*exc_info)
File "C:\Users\Shobhit\Anaconda3\envs\py38\lib\site‑packages\zmq\utils\sixcerpt.py", line 34, in reraise
raise value
File "C:\Users\Shobhit\Anaconda3\envs\py38\lib\site‑packages\zmq\backend\__init__.py", line 27, in 
_ns = select_backend(first)
File "C:\Users\Shobhit\Anaconda3\envs\py38\lib\site‑packages\zmq\backend\select.py", line 28, in select_backend
mod = __import__(name, fromlist=public_api)
File "C:\Users\Shobhit\Anaconda3\envs\py38\lib\site‑packages\zmq\backend\cython\__init__.py", line 6, in 
from . import (constants, error, message, context,
ImportError: DLL load failed while importing error: The specified module could not be found.

**Comment by fserra** [comment]
give http://www.pokutta.com/blog/pages/scip/scip-teaching.html a try.

You said you downloaded SCIP and extract it somewhere. If you are on windows you need to download the executable of the scipoptsuite and not the source code

**Comment by Shobhitp2018** [comment]
ok ,i have downloaded the scip executables .

**Comment by fserra** [comment]
ok, and?
