### ISSUE TITLE
Problems regarding installation of PySCIPOpt

### ISSUE THREAD

**Issue by ereday** [scipopt/PySCIPOpt#479]
Hi,

I have some issues regarding installing PySCIPOpt. I have already read both open & closed issues but unfortunately none of the previous suggestions worked for me.  I have locally build SCIP with CMake (as suggested). For that, I did the followings:

```
tar xvfz scipoptsuite-7.0.2.tgz
cd scipoptsuite-7.0.2
mkdir build
cd build
export DESTDIR='~/scip_dest_dir' # to force cmake to run locally
cmake .. -DSOPLEX_DIR=./../soplex
make
make install
```

After these steps, I am able to run SCIP via terminal. Next, I set SCIPOPTDIR and DYLD_LIBRARY_PATH variables.(Btw, installation instructions don't say anything about DYLD_LIBRARY_PATH variable. I found out that this variable should be set on closed issues)

```
export SCIPOPTDIR=~/scip_dest_dir/usr/local
export DYLD_LIBRARY_PATH=~/scip_dest_dir/usr/local/lib/
```

Then, I install PySCIPOpt as follows:
```
python -m pip install pyscipopt
Collecting pyscipopt
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/48/51/c55f740d954fb7bc964dcba07f966b7bc79d47da22be26cab2f2229ff4f9/PySCIPOpt-3.1.0.tar.gz (619kB)
    100% |████████████████████████████████| 624kB 809kB/s
Installing collected packages: pyscipopt
  Running setup.py install for pyscipopt ... done
Successfully installed pyscipopt-3.1.0
You are using pip version 9.0.3, however version 21.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

Next, I tried to import it and got the following error:
```
$ python
>>> from pyscipopt import Model
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/virtual-environments/foo/lib/python3.6/site-packages/pyscipopt/__init__.py", line 11, in <module>
    from pyscipopt.scip      import Model
ImportError: ~/anaconda3/lib/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by ~/scip_dest_dir/usr/local/lib/libscip.so.7.0)
```

I have already checked if GLIBCXX_3.4.26 is available on the system or not as follows:

```
$ strings /usr/lib/libstdc++.so.6 | grep GLIBC

GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_3.4.23
GLIBCXX_3.4.24
GLIBCXX_3.4.25
GLIBCXX_3.4.26
```

So, what should I do for fixing this problem? Thanks!

Information about my environment:
```
$  lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 33 (Thirty Three)
Release:	33
Codename:	ThirtyThree
```

**Comment by ereday** [comment]
I've just realized that my anaconda environment is broken in some way. It works with another python environment.
