### ISSUE TITLE
MemoryError: SCIP: insufficient memory error

### ISSUE THREAD

**Issue by littlebaba** [scipopt/PySCIPOpt#517]
I'm getting the following error after solving an MINLP problem.

```
> presolving:
> 
> [C:\Jenkins\workspace\SCIPOptSuite_windows_libs_release\scipoptsuite-7.0.2\scip\src\blockmemshell\memory.c:1059] ERROR: Insufficient memory for allocation of 1198432 bytes.
> 
> [C:\Jenkins\workspace\SCIPOptSuite_windows_libs_release\scipoptsuite-7.0.2\scip\src\nlpi\expr.c:9518] ERROR: Insufficient memory for new chunk.
> 
> [expr.c:9518] ERROR: No memory in function call
> 
> [expr.c:11684] ERROR: Error <-1> in function call
> 
> [expr.c:16092] ERROR: Error <-1> in function call
> 
> [cons_nonlinear.c:8324] ERROR: Error <-1> in function call
> 
> [cons.c:4059] ERROR: Error <-1> in function call
> 
> [scip_solve.c:1008] ERROR: Error <-1> in function call
> 
> [scip_solve.c:1378] ERROR: Error <-1> in function call
> 
> [scip_solve.c:2398] ERROR: Error <-1> in function call
> 
> [scip_solve.c:2620] ERROR: Error <-1> in function call
> 
> Traceback (most recent call last):
> 
>   File "D:\soft\programsoft\JetBrains\PyCharm 2020.1.3\plugins\python\helpers\pydev\pydevd.py", line 1438, in _exec
> 
>    pydev_imports.execfile(file, globals, locals)  # execute the script
> 
>   File "D:\soft\programsoft\JetBrains\PyCharm 2020.1.3\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
> 
>     exec(compile(contents+"\n", file, 'exec'), glob, loc)
> 
>   File "F:/2020pro/pypro/resultanalysis/LPJCX_SCIP.py", line 167, in <module>
> 
>     app = Main()
> 
>   File "F:/2020pro/pypro/resultanalysis/LPJCX_SCIP.py", line 40, in __init__
> 
>     self.solve(Matrix, c)
> 
>   File "F:/2020pro/pypro/resultanalysis/LPJCX_SCIP.py", line 143, in solve
> 
>     model.optimize()
> 
>   File "src\pyscipopt\scip.pyx", line 3093, in pyscipopt.scip.Model.optimize
> 
>   File "src\pyscipopt\scip.pyx", line 234, in pyscipopt.scip.PY_SCIP_CALL
> 
> MemoryError: SCIP: insufficient memory error!
> 
>    (57.0s) symmetry computation skipped: there exist constraints that cannot be handled by symmetry methods.
```

I can't retrieve the solution after this happens. Is there a way to avoid this?
Thank you.

**Comment by CGraczyk** [comment]
@fschloesser any idea?

**Comment by fschloesser** [comment]
@littlebaba can you please provide more information about this, what is the system and what are its memory specifications? Which SCIP and PySCIPOpt versions are you using? Does this problem also happen when you write out the problem that you generate with pyscipopt to a file and then solve that with SCIP?
