### ISSUE TITLE
installation problem on mac m1

### ISSUE THREAD

**Issue by feidapeng** [scipopt/PySCIPOpt#528]
- MacBook Pro (13-inch, M1, 2020),   macOS Big Sur 11.5
- download scipoptsuite-7.0.1.tgz , and install like this
```
mkdir setup
cd setup
cmake ..
make
make install
```
- run scip in the command successfuly
- Successfully installed pyscipopt-3.0.0 with pip
 
But if i import model this error occures:

```
>>> import pyscipopt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/fay/opt/anaconda3/lib/python3.8/site-packages/pyscipopt/__init__.py", line 10, in <module>
    from pyscipopt.scip      import Model
ImportError: dlopen(/Users/fay/opt/anaconda3/lib/python3.8/site-packages/pyscipopt/scip.cpython-38-darwin.so, 2): Symbol not found: _SCIPactivateBenders
  Referenced from: /Users/fay/opt/anaconda3/lib/python3.8/site-packages/pyscipopt/scip.cpython-38-darwin.so
  Expected in: flat namespace
 in /Users/fay/opt/anaconda3/lib/python3.8/site-packages/pyscipopt/scip.cpython-38-darwin.so
```

then I checked "scip.cpython-38-darwin.so"  : `sudo otool -L /Users/fay/opt/anaconda3/lib/python3.8/site-packages/pyscipopt/scip.cpython-38-darwin.so`, what I got is
```
/Users/fay/opt/anaconda3/lib/python3.8/site-packages/pyscipopt/scip.cpython-38-darwin.so:
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.100.5)
```
but the file "/usr/lib/libSystem.B.dylib" not exists, so i changed the softlink:
```
sudo install_name_tool -change /usr/lib/libSystem.B.dylib /usr/local/lib/libscip.7.0.dylib /Users/fay/opt/anaconda3/lib/python3.8/site-packages/pyscipopt/scip.cpython-38-darwin.so
```
when I import model again, See error below...
```
>>> import pyscipopt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/fay/opt/anaconda3/lib/python3.8/site-packages/pyscipopt/__init__.py", line 10, in <module>
    from pyscipopt.scip      import Model
ImportError: dlopen(/Users/fay/opt/anaconda3/lib/python3.8/site-packages/pyscipopt/scip.cpython-38-darwin.so, 2): Library not loaded: /usr/local/lib/libscip.7.0.dylib
  Referenced from: /Users/fay/opt/anaconda3/lib/python3.8/site-packages/pyscipopt/scip.cpython-38-darwin.so
  Reason: no suitable image found.  Did find:
	/Users/fay/opt/scipoptsuite-7.0.1/setup/lib/libscip.7.0.dylib: mach-o, but wrong architecture
	/Users/fay/opt/scipoptsuite-7.0.1/setup/lib/libscip.7.0.1.0.dylib: mach-o, but wrong architecture
	/usr/local/lib/libscip.7.0.dylib: mach-o, but wrong architecture
	/usr/local/lib/libscip.7.0.dylib: mach-o, but wrong architecture
	/usr/local/lib/libscip.7.0.1.0.dylib: mach-o, but wrong architecture
	/usr/local/lib/libscip.7.0.1.0.dylib: mach-o, but wrong architecture
>>>
```

**Comment by feidapeng** [comment]
I tried to specify the `DYLD_LIBRARY_PATH=/Users/fay/opt/scipoptsuite-7.0.1/setup/lib`, but it was of no use.

**Comment by feidapeng** [comment]
It was caused by conda's version， when i change anaconda from x86_64 to arm64, it works!
