### ISSUE TITLE
`ImportError: libscip.so.7.0: cannot open shared object file: No such file or directory`

### ISSUE THREAD

**Issue by SightVanish** [scipopt/PySCIPOpt#622]
Here is what I did:

1. download `scipoptsuite-7.0.3.tgz`
2. `cd scipoptsuite-7.0.3`, `mkdir build`, `cd build`, `cmake .. -DSYM=bliss -DWORHP=off -DZIMPL=off -DTPI=tny -DPARASCIP=on -DIPOPT=off -DPAPILO=off`, `make`, `make install`
3. `export SCIPOPTDIR=~/scipoptsuite-7.0.3/install/`
4. `pip install pyscipopt==3.5.0 `

Everything works fine, but

```shell
>>>from pyscipopt import Model
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/liwuchen/anaconda3/envs/port/lib/python3.6/site-packages/pyscipopt/__init__.py", line 11, in <module>
    from pyscipopt.scip      import Model
ImportError: libscip.so.7.0: cannot open shared object file: No such file or directory
```

`libscip.so.7.0` did exist

```shell
$ ls ~/scipoptsuite-7.0.3/install/lib
cmake      libgcg.so.3.0      libscip.so      libscip.so.7.0.3.0  libsoplex.a
libgcg.so  libgcg.so.3.0.5.0  libscip.so.7.0  libsoplex-pic.a
```

I am working on Ubuntu20, WSL2, python3.6.

I guess it may be caused by path problem, so I tried this

```shell
$ cat /etc/ld.so.conf
include /etc/ld.so.conf.d/*.conf
/usr/local/lib/
/home/usrname/scipoptsuite-7.0.3/install/lib/
```

Not worked. What should I do?

**Comment by SightVanish** [comment]
I just copied `libscip.so.7.0` form `/home/usrname/scipoptsuite-7.0.3/install/lib/` to `/usr/local/` and it worked.

But I still can not pass `pytest`.

**Comment by Joao-Dionisio** [comment]
Hello, @SightVanish! Sorry for the very long time to answer. Are you still having problems?

**Comment by fr-ukun** [comment]
@Joao-Dionisio Hello, I'm facing same problem.

```bash
$ python3 -c "import pyscipopt"                                                                                                                                                                                                                                       Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/username/myproject/.venv/lib/python3.10/site-packages/pyscipopt/__init__.py", line 11, in <module>
    from pyscipopt.scip      import Model
ImportError: dlopen(/Users/username/myproject/.venv/lib/python3.10/site-packages/pyscipopt/scip.cpython-310-darwin.so, 2): Library not loaded: libscip.8.0.dylib
  Referenced from: /Users/username/myproject/.venv/lib/python3.10/site-packages/pyscipopt/scip.cpython-310-darwin.so
  Reason: image not found
```

I'm working on MacOS (BigSur 11.6.3), and Python 3.10.3.
```bash
$ uname -rsvp
Darwin 20.6.0 Darwin Kernel Version 20.6.0: Wed Jan 12 22:22:42 PST 2022; root:xnu-7195.141.19~2/RELEASE_X86_64 i386
```

I installed scipoptsuite to `/Users/username/scipopt/lib` and `libscip.8.0.dylib` did exist.
```
$ env | grep SCIP
SCIPOPTDIR=/Users/username/scipopt/
$ pwd
/Users/username/scipopt/lib
$ ls
cmake/                         libgcg.3.5.3.0.dylib*          libgcg.dylib@                  libscip.8.0.dylib@             libsoplex-pic.a                libsoplexshared.6.0.3.0.dylib* libsoplexshared.dylib@         libzimpl.a
libbliss.a                     libgcg.3.5.dylib@              libscip.8.0.3.0.dylib*         libscip.dylib@                 libsoplex.a                    libsoplexshared.6.0.dylib@     libzimpl-pic.a
```

When I ran cmake to installe scipoptsuite, I ran `cmake .. -DCMAKE_INSTALL_PREFIX=~/scipopt -DAUTOBUILD=ON`.

**Comment by fr-ukun** [comment]
After I add `lib` directory to `DYLD_LIBRARY_PATH`, then it worked.
```fish
set -x DYLD_LIBRARY_PATH /Users/username/scipopt/lib $DYLD_LIBRARY_PATH
```

**Comment by Joao-Dionisio** [comment]
I am closing the issue to clear the Issue page, but feel free to reopen it if you are still having problems!
