### ISSUE TITLE
inheritance in scip classes 

### ISSUE THREAD

**Issue by joaopedroso** [scipopt/PySCIPOpt#633]
I have been trying to implement an interface for using PySCIPOpt on simple gurobipy examples but I am facing some difficulties, mainly from not being able to inherit SCIP interface classes' properties. Is there any way of doing so?
Thanks!
jpp

--
```
from pyscipopt import Model as ScipModel
from pyscipopt.scip import Variable as ScipVariable

# case 1
class Model(ScipModel):
   def __init__(self, name='model'):
       ScipModel.__init__(self, name)
       self._vars = []

   def addVar(self, *args, **kwargs):
       pyVar = ScipModel.addVar(self, *args, **kwargs)
       pyvar.X = something   # ERROR, cannot add properties


# case 2
class Variable(ScipVariable):
   def __init__(self, var):
       self.scip_var = var.scip_var.  # —> ERROR
   # add other functionalities

class Model(ScipModel):
   def __init__(self, name='model'):
       ScipModel.__init__(self, name)

   def addVar(self, *args, **kwargs):
       pyVar = ScipModel.addVar(self, *args, **kwargs)
       newvar = Variable(pyVar)
```

**Comment by joaopedroso** [comment]
Thanks Felipe, but I think that doesn’t solve my problem.

I would need to hijack SCIP’s model so that, e.g., addVar would return an object that besides being usable in an expression had the attribute X, so that var.X would behave as with Gurobi (return the optimal value).  I am not seeing how to do it in a simple way if SCIP’s Variable class cannot be subclassed, and that attribute added...

Maybe I am missing something?

jpp

**Comment by Joao-Dionisio** [comment]
This doesn't answer the question of inheritance, but unless I misunderstood, one can use [model.getVal(var)](https://scipopt.github.io/PySCIPOpt/docs/html/classpyscipopt_1_1scip_1_1Model.html#a72eca242798303e1f0bc4a11156eaca6) to get the value of a variable in the optimal solution. If we have a solution s, we can also use [model.getSolVal(s,var)](https://scipopt.github.io/PySCIPOpt/docs/html/classpyscipopt_1_1scip_1_1Model.html#adfdb30613137bed972a061c84632667b).

**Comment by fserra** [comment]
I don't think `var.getUb/LbGlobal()` give you the value at the optimal solution.

A somewhat horrible way of achieving what you want is something like:
1. extend `__init__.py` with `from pyscipopt.scip      import Variable`
2. Then you can create:
```py
class MyVar(Variable):
    def __init__(self, model, name='', vtype='C', lb=0.0, ub=None, obj=0.0, pricedVar=False, pricedVarScore=1.0):
        self._model = model
        self._var = model.addVar(name, vtype, lb, ub, obj, pricedVar, pricedVarScore)

    @property
    def X(self):
        return self._model.getVal(self._var)
    @property
    def var(self):
        return self._var
```

This should do it, but looks very nasty.

I tested it in `test_alldiff` after changing it a bit:
```diff
diff --git a/tests/test_alldiff.py b/tests/test_alldiff.py
index efe9bec..4a64de4 100644
--- a/tests/test_alldiff.py
+++ b/tests/test_alldiff.py
@@ -2,7 +2,7 @@ import pytest
 
 networkx = pytest.importorskip("networkx")
 
-from pyscipopt import Model, Conshdlr, SCIP_RESULT, SCIP_PARAMEMPHASIS, SCIP_PARAMSETTING
+from pyscipopt import Model, Variable, Conshdlr, SCIP_RESULT, SCIP_PARAMEMPHASIS, SCIP_PARAMSETTING
 
 try:
     from types import SimpleNamespace
@@ -210,6 +210,17 @@ class ALLDIFFconshdlr(Conshdlr):
         #print("CONSTRANS BEING CAAAAAAAAAAAAAAAAAAAALLLLLLED")
         return {}
 
+class MyVar(Variable):
+    def __init__(self, model, name='', vtype='C', lb=0.0, ub=None, obj=0.0, pricedVar=False, pricedVarScore=1.0):
+        self._model = model
+        self._var = model.addVar(name, vtype, lb, ub, obj, pricedVar, pricedVarScore)
+
+    @property
+    def X(self):
+        return self._model.getVal(self._var)
+    @property
+    def var(self):
+        return self._var
 
 # builds sudoku model; adds variables and all diff constraints
 def create_sudoku():
@@ -220,9 +231,9 @@ def create_sudoku():
         for col in range(9):
             # some variables are fix
             if init[row*9 + col] != 0:
-                x[row,col] = scip.addVar(vtype = "I", lb = init[row*9 + col], ub = init[row*9 + col], name = "x(%s,%s)" % (row,col))
+                x[row,col] = MyVar(scip, vtype = "I", lb = init[row*9 + col], ub = init[row*9 + col], name = "x(%s,%s)" % (row,col))
             else:
-                x[row,col] = scip.addVar(vtype = "I", lb = 1, ub = 9, name = "x(%s,%s)" % (row,col))
+                x[row,col] = MyVar(scip, vtype = "I", lb = 1, ub = 9, name = "x(%s,%s)" % (row,col))
             var = x[row,col]
             #print("built var ", var.name, " with bounds: (%d,%d)"%(var.getLbLocal(), var.getUbLocal()))
 
@@ -238,7 +249,7 @@ def create_sudoku():
     for row in range(9):
         vars = []
         for col in range(9):
-            var = x[row,col]
+            var = x[row,col].var
             vars.append(var)
             vals = set(range(int(round(var.getLbLocal())), int(round(var.getUbLocal())) + 1))
             domains[var.ptr()] = vals
@@ -254,7 +265,7 @@ def create_sudoku():
     for col in range(9):
         vars = []
         for row in range(9):
-            var = x[row,col]
+            var = x[row,col].var
             vars.append(var)
         cons = scip.createCons(conshdlr, "col_%d"%col)
         cons.data = SimpleNamespace()
@@ -268,7 +279,7 @@ def create_sudoku():
             vars = []
             for row in range(3):
                 for col in range(3):
-                    var = x[3*idx1 + row, 3*idx2 + col]
+                    var = x[3*idx1 + row, 3*idx2 + col].var
                     vars.append(var)
             cons = scip.createCons(conshdlr, "square_%d-%d"%(idx1, idx2))
             cons.data = SimpleNamespace()
@@ -297,7 +308,7 @@ def test_main():
         for row in range(9):
             out = ''
             for col in range(9):
-                out += str(round(scip.getVal(x[row,col]))) + ' '
+                out += str(round(x[row,col].X)) + ' '
             print(out)
 
 if __name__ == "__main__":
```

**Comment by joaopedroso** [comment]
I'm fine if it is awkward, I don't see any elegant alternative.
How should I change `Variable` class in the example below for behaving as usual in PySCIPOpt?
Current code leads to
```
Traceback (most recent call last):
  File "/Users/jpp/SHARE/bugs/KUBO/2022/myscipopt/tests/test_myscipopt.py", line 15, in <module>
    m.addConstr(X >= Y)
  File "src/pyscipopt/expr.pxi", line 270, in pyscipopt.scip.Expr.__richcmp__
  File "src/pyscipopt/expr.pxi", line 67, in pyscipopt.scip._expr_richcmp
  File "src/pyscipopt/expr.pxi", line 257, in pyscipopt.scip.Expr.__sub__
  File "src/pyscipopt/expr.pxi", line 254, in pyscipopt.scip.Expr.__neg__
AttributeError: 'NoneType' object has no attribute 'items'
```

Thanks!
jpp

```
from pyscipopt import Model as ScipModel
from pyscipopt.scip import Variable as ScipVariable

class Variable(ScipVariable):
    def __init__(self, model, *args, **kwargs):
        self._model = model
        self._var = ScipModel.addVar(model, *args, **kwargs)

    @property
    def X(self):
        return self._model.getVal(self._var)

    @property
    def var(self):
        return self._var


class Model(ScipModel):
    def __init__(self, *args, **kwargs):
        ScipModel.__init__(self, *args, **kwargs)

    def addVar(self, *args, **kwargs):
        return Variable(self, *args, **kwargs)

    def addConstr(self, *args, **kwargs):
        return ScipModel.addCons(self, *args, **kwargs)


if __name__ == "__main__":
    m = Model()
    print("started model")

    X = m.addVar(ub=3.0, name="X")
    Y = m.addVar(ub=3.0, name="Y")
    print("added variables")

    m.addConstr(X >= Y)
    print("added a constraint")
```

**Comment by fserra** [comment]
mmm on a second thought it seems to be useless to extend the class `Variable` (`ScipVariable` in your case) since nothing from that class is being used. Then you don't need to expose it in the `__init__.py`

I guess you would need to re-implement the behavior, something like:
```py
    def __ge__(self, other):
        return self._var >= other._var
```
so the whole class would look like:
```py
class Variable():
    def __init__(self, model, *args, **kwargs):
        self._model = model
        self._var = ScipModel.addVar(model, *args, **kwargs)

    @property
    def X(self):
        return self._model.getVal(self._var)

    @property
    def var(self):
        return self._var

    def __ge__(self, other):
        return self._var >= other._var
```

**Comment by joaopedroso** [comment]
But then it would not behave as expected in expressions:
```
    m.addConstr(5 + 3*X >= Y/4)
```
would lead to
```
Traceback (most recent call last):
  File "/Users/jpp/Library/Application Support/JetBrains/PyCharm2021.2/scratches/scratch_3.py", line 42, in <module>
    m.addConstr(5 + 3*X >= Y/4)
TypeError: unsupported operand type(s) for *: 'int' and 'Variable'
```

**Comment by fserra** [comment]
mmm you can keep on hacking it:
```py
class Variable():
    def __init__(self, model, *args, **kwargs):
        self._model = model
        self._var = ScipModel.addVar(model, *args, **kwargs)

    @property
    def X(self):
        return self._model.getVal(self._var)

    @property
    def var(self):
        return self._var

    def __ge__(self, other):
        return self._var >= other._var

    def __mul__(self, other):
        return self._var * other
    def __rmul__(self, other):
        return self._var * other
```

then
```py
    m.addConstr(3*X >= 1*Y)
```
works for me. But apparently, the `1*Y` is needed to transform it into an expression... pretty horrible

**Comment by joaopedroso** [comment]
Well... at first I thought it should be pretty straightforward to implement the interface, but it seems to be rather tricky, mainly because of Variable/addVar.

**Comment by Joao-Dionisio** [comment]
I am closing the issue to clear the Issues page, but feel free to reopen it if you think it makes sense!
