### ISSUE TITLE
The issue to use PySCIPopt on colab 

### ISSUE THREAD

**Issue by abb-omidi** [scipopt/PySCIPOpt#658]
Dear support team,

I hope you are doing well. I worked on the PySCIPopt on my local machine and everything went well. Now, I would like to run my model in the Google-Colab and I have some issues to do this. I took a look at this [link](https://stackoverflow.com/a/72754714/7414813) as @mattmilten answered the question. The conda and its related libraries about SCIP install completely except for some things, but when I run the code I have the following error:

```
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-8-7e535bd47dff>](https://localhost:8080/#) in <module>
----> 1 from pyscipopt import Model
      2 m = Model()
      3 m.redirectOutput()
      4 m.printVersion()

ModuleNotFoundError: No module named 'pyscipopt'
```

 
The exceptional conda installation:
```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: done
...
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Retrieving notices: ...working... failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/conda/exceptions.py", line 1129, in __call__
  File "/usr/local/lib/python3.8/site-packages/conda/cli/main.py", line 86, in main_subshell
  File "/usr/local/lib/python3.8/site-packages/conda/cli/conda_argparse.py", line 93, in do_call
  File "/usr/local/lib/python3.8/site-packages/conda/notices/core.py", line 75, in wrapper
  File "/usr/local/lib/python3.8/site-packages/conda/notices/core.py", line 39, in display_notices
  File "/usr/local/lib/python3.8/site-packages/conda/notices/http.py", line 36, in get_notice_responses
  File "/usr/local/lib/python3.8/site-packages/conda/notices/http.py", line 39, in <genexpr>
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 444, in result
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
  File "/usr/local/lib/python3.8/site-packages/conda/notices/http.py", line 42, in <lambda>
  File "/usr/local/lib/python3.8/site-packages/conda/notices/cache.py", line 37, in wrapper
  File "/usr/local/lib/python3.8/site-packages/conda/notices/http.py", line 58, in get_channel_notice_response
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 600, in get
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 460, in send
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 263, in cert_verify
OSError: Could not find a suitable TLS CA certificate bundle, invalid path: /usr/local/lib/python3.8/site-packages/certifi/cacert.pem

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/conda", line 15, in <module>
  File "/usr/local/lib/python3.8/site-packages/conda/cli/main.py", line 129, in main
  File "/usr/local/lib/python3.8/site-packages/conda/exceptions.py", line 1429, in conda_exception_handler
  File "/usr/local/lib/python3.8/site-packages/conda/exceptions.py", line 1132, in __call__
  File "/usr/local/lib/python3.8/site-packages/conda/exceptions.py", line 1172, in handle_exception
  File "/usr/local/lib/python3.8/site-packages/conda/exceptions.py", line 1183, in handle_unexpected_exception
  File "/usr/local/lib/python3.8/site-packages/conda/exceptions.py", line 1245, in print_unexpected_error_report
ModuleNotFoundError: No module named 'conda.cli.main_info'
```

The Colab-link can be found [here](https://colab.research.google.com/drive/1yMzd2eOAH96EhGAH3RZZIRpSe-LLa7hg?usp=sharing).
I was wondering if, how can I fix that?

Best regards
Abbas

**Comment by Joao-Dionisio** [comment]
Hello, @abb-omidi! I am doing well, thank you, I hope you are as well :)

I am not familiar with Google Colab, or with using Anaconda on Google Colab. However, when installing PySCIPOPT via anaconda locally, we must not use the conda base environment (see here the [Instalation](https://github.com/scipopt/PySCIPOpt#installation)), but rather create a new one and install it there. Do you think this might be causing the issue?

**Comment by abb-omidi** [comment]
Dear Joao (@Joao-Dionisio),

Thanks for your attention. I do not familiar with Conda and its environment well. Hence, I go with the pointed out steps by @mattmilten. Also, I tried to run what you mentioned, but the issue is remaning. If you can fix that, would you please, do that or describe how I do it in the detail. 

Regards
Abbas

**Comment by mattmilten** [comment]
It runs just fine using

```
!conda install pyscipopt
```

without the additional conda commands that have been in your notebook:
<img width="1081" alt="image" src="https://user-images.githubusercontent.com/1506995/224791658-b600c67e-e659-4b83-b79d-dc01bac25cff.png">

**Comment by abb-omidi** [comment]
Dear @mattmilten ,

Have you updated any internal functions!!? It works now like a charm. It is very strange as @Joao-Dionisio had the same experience too. BTW, thank you so much.

Regards
Abbas

**Comment by mattmilten** [comment]
No, I did not change anything... great to hear that it works on your end as well, now!
