### ISSUE TITLE
ImportError: libtbb.so.12: cannot open shared object file: No such file or directory`

### ISSUE THREAD

**Issue by DigitalGabriele** [scipopt/PySCIPOpt#726]
I compiled scipoptsuite-8.0.4 from source and exported the path of to /usr/local

Then I cloned the PySCIPOpt repository and ran:

`python -m pip install .`

Now I am trying to run my simple code with PySCIPOpt in it and I am getting the following error:

`(base) ubuntu@ubuntu-desktop:~$ python3 static_using_scip.py 
Traceback (most recent call last):
  File "/home/ubuntu/static_using_scip.py", line 8, in <module>
    from pyscipopt import Model, quicksum
  File "/home/ubuntu/miniforge3/lib/python3.10/site-packages/pyscipopt/__init__.py", line 11, in <module>
    from pyscipopt.scip      import Model
ImportError: libtbb.so.12: cannot open shared object file: No such file or directory`

I saw somewhere online to install libtbb by running:

`sudo apt-get install libtbb2` or `conga install tbb=2020.2 `

I ran them both but neither worked. I get the same error. 

How can I solve this?

**Comment by Joao-Dionisio** [comment]
Hello again, @DigitalGabriele! Did you follow the steps from [Install.md](https://github.com/scipopt/PySCIPOpt/blob/master/INSTALL.md) precisely? Does your SCIP installation work? Is the SCIPOPTDIR correctly set up? Meaning, does it point to the subdirectories mentioned in the installation guide?

**Comment by DigitalGabriele** [comment]
How do I properly test my SCIP installation? I saw [here](https://www.scipopt.org/doc/html/md_INSTALL.php#CMAKE) that you can run `ctest -N`. Where are you supposed to run this line? I installed SCIP in `~/scipoptsuite-8.0.4/`

I set SCIPOPTDIR to /user/local

I set the wrong SCIPOPTDIR in the beginning, but after I changed it to /user/local, I got the above error.

**Comment by Joao-Dionisio** [comment]
I mean trying to use SCIP to solve a problem.

Also, I'd recommend going for the anaconda installation, if you can, it's definitely easier.

**Comment by DigitalGabriele** [comment]
> I mean trying to use SCIP to solve a problem.

Isn't that what I am doing? I have a python script called static_using_scip.py that I am trying to run. But it won't work because I need PySCIPOpt for it. 

> Also, I'd recommend going for the anaconda installation, if you can, it's definitely easier.

I tried anaconda, but then I thought I had to do it from source since I am running it on aarch64. I will retry installing with conda when I do it in a new environment. I wonder what I did wrong though.

**Comment by Joao-Dionisio** [comment]
> Isn't that what I am doing? 

No, PySCIPOpt is the Python interface for the solver SCIP. I meant opening scip in your command line and using it directly to solve a problem. To do this, the simplest way would be to have an optimization problem in a readable file format (like ```mps``` for example), and then use the ```read``` command and afterwards the ```optimize``` command.


> I wonder what I did wrong though.
 In relation to this, it's hard to tell, as there is too much stuff that can happen, and I am also not very proficient in doing things like this :/

**Comment by DigitalGabriele** [comment]
Anaconda didn't work, I got the following error:

`PackagesNotFoundError: The following packages are not available from current channels:

  - pyscipopt

Current channels:

  - https://conda.anaconda.org/conda-forge/linux-aarch64
  - https://conda.anaconda.org/conda-forge/noarch`


I also tried running these commands: 
`(base) ubuntu@ubuntu-desktop:~/PySCIPOpt$ python -m pip install pyscipopt

Requirement already satisfied: pyscipopt in /home/ubuntu/miniforge3/lib/python3.10/site-packages (4.3.0)`

It seems like pyscipopt is installed? Then I ran py.test and got:

`(base) ubuntu@ubuntu-desktop:~/PySCIPOpt$ py.test
================================================== test session starts ===================================================
platform linux -- Python 3.10.12, pytest-7.4.2, pluggy-1.3.0
rootdir: /home/ubuntu/PySCIPOpt
configfile: setup.cfg
testpaths: tests
collected 0 items / 31 errors / 1 skipped                                                                                

========================================================= ERRORS =========================================================
_________________________________________ ERROR collecting tests/test_benders.py _________________________________________
ImportError while importing test module '/home/ubuntu/PySCIPOpt/tests/test_benders.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../miniforge3/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_benders.py:9: in <module>
    from pyscipopt import Model, quicksum, multidict, SCIP_PARAMSETTING
../miniforge3/lib/python3.10/site-packages/pyscipopt/__init__.py:11: in <module>
    from pyscipopt.scip      import Model
E   ImportError: libtbb.so.12: cannot open shared object file: No such file or directory
____________________________________ ERROR collecting tests/test_branch_probing_lp.py ____________________________________
ImportError while importing test module '/home/ubuntu/PySCIPOpt/tests/test_branch_probing_lp.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../miniforge3/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_branch_probing_lp.py:1: in <module>
    from pyscipopt import Model, Branchrule, SCIP_RESULT, quicksum
../miniforge3/lib/python3.10/site-packages/pyscipopt/__init__.py:11: in <module>
    from pyscipopt.scip      import Model
E   ImportError: libtbb.so.12: cannot open shared object file: No such file or directory
________________________________________ ERROR collecting tests/test_conshdlr.py _________________________________________
ImportError while importing test module '/home/ubuntu/PySCIPOpt/tests/test_conshdlr.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../miniforge3/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_conshdlr.py:1: in <module>
    from pyscipopt import Model, Conshdlr, SCIP_RESULT, SCIP_PRESOLTIMING, SCIP_PROPTIMING
../miniforge3/lib/python3.10/site-packages/pyscipopt/__init__.py:11: in <module>
    from pyscipopt.scip      import Model
E   ImportError: libtbb.so.12: cannot open shared object file: No such file or directory
__________________________________________ ERROR collecting tests/test_copy.py ___________________________________________
ImportError while importing test module '/home/ubuntu/PySCIPOpt/tests/test_copy.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../miniforge3/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_copy.py:1: in <module>
    from pyscipopt import Model
../miniforge3/lib/python3.10/site-packages/pyscipopt/__init__.py:11: in <module>
    from pyscipopt.scip      import Model
E   ImportError: libtbb.so.12: cannot open shared object file: No such file or directory
____________________________________ ERROR collecting tests/test_customizedbenders.py ____________________________________
ImportError while importing test module '/home/ubuntu/PySCIPOpt/tests/test_customizedbenders.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../miniforge3/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_customizedbenders.py:9: in <module>
    from pyscipopt import Model, quicksum, multidict, SCIP_PARAMSETTING, Benders,\
../miniforge3/lib/python3.10/site-packages/pyscipopt/__init__.py:11: in <module>
    from pyscipopt.scip      import Model
E   ImportError: libtbb.so.12: cannot open shared object file: No such file or directory
_________________________________________ ERROR collecting tests/test_cutsel.py __________________________________________
ImportError while importing test module '/home/ubuntu/PySCIPOpt/tests/test_cutsel.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../miniforge3/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_cutsel.py:1: in <module>
    from pyscipopt import Model, quicksum, SCIP_RESULT, SCIP_PARAMSETTING
../miniforge3/lib/python3.10/site-packages/pyscipopt/__init__.py:11: in <module>
    from pyscipopt.scip      import Model
E   ImportError: libtbb.so.12: cannot open shared object file: No such file or directory
__________________________________________ ERROR collecting tests/test_event.py __________________________________________
ImportError while importing test module '/home/ubuntu/PySCIPOpt/tests/test_event.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../miniforge3/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_event.py:3: in <module>
    from pyscipopt import Model, Eventhdlr, SCIP_RESULT, SCIP_EVENTTYPE, SCIP_PARAMSETTING
../miniforge3/lib/python3.10/site-packages/pyscipopt/__init__.py:11: in <module>
    from pyscipopt.scip      import Model
E   ImportError: libtbb.so.12: cannot open shared object file: No such file or directory
__________________________________________ ERROR collecting tests/test_expr.py ___________________________________________
ImportError while importing test module '/home/ubuntu/PySCIPOpt/tests/test_expr.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../miniforge3/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_expr.py:3: in <module>
    from pyscipopt import Model, sqrt, log, exp, sin, cos
../miniforge3/lib/python3.10/site-packages/pyscipopt/__init__.py:11: in <module>
    from pyscipopt.scip      import Model
E   ImportError: libtbb.so.12: cannot open shared object file: No such file or directory
_________________________________________ ERROR collecting tests/test_gomory.py __________________________________________
ImportError while importing test module '/home/ubuntu/PySCIPOpt/tests/test_gomory.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../miniforge3/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_gomory.py:3: in <module>
    from pyscipopt import Model, Sepa, SCIP_RESULT, SCIP_PARAMSETTING
../miniforge3/lib/python3.10/site-packages/pyscipopt/__init__.py:11: in <module>
    from pyscipopt.scip      import Model
E   ImportError: libtbb.so.12: cannot open shared object file: No such file or directory
__________________________________________ ERROR collecting tests/test_heur.py ___________________________________________
ImportError while importing test module '/home/ubuntu/PySCIPOpt/tests/test_heur.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../miniforge3/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_heur.py:6: in <module>
    from pyscipopt import Model, Heur, SCIP_RESULT, SCIP_PARAMSETTING, SCIP_HEURTIMING
../miniforge3/lib/python3.10/site-packages/pyscipopt/__init__.py:11: in <module>
    from pyscipopt.scip      import Model
E   ImportError: libtbb.so.12: cannot open shared object file: No such file or directory
________________________________________ ERROR collecting tests/test_knapsack.py _________________________________________
ImportError while importing test module '/home/ubuntu/PySCIPOpt/tests/test_knapsack.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../miniforge3/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_knapsack.py:1: in <module>
    from pyscipopt import Model, quicksum
../miniforge3/lib/python3.10/site-packages/pyscipopt/__init__.py:11: in <module>
    from pyscipopt.scip      import Model
E   ImportError: libtbb.so.12: cannot open shared object file: No such file or directory
_________________________________________ ERROR collecting tests/test_linexpr.py _________________________________________
ImportError while importing test module '/home/ubuntu/PySCIPOpt/tests/test_linexpr.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../miniforge3/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_linexpr.py:3: in <module>
    from pyscipopt import Model
../miniforge3/lib/python3.10/site-packages/pyscipopt/__init__.py:11: in <module>
    from pyscipopt.scip      import Model
E   ImportError: libtbb.so.12: cannot open shared object file: No such file or directory
_________________________________________ ERROR collecting tests/test_logical.py _________________________________________
ImportError while importing test module '/home/ubuntu/PySCIPOpt/tests/test_logical.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../miniforge3/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_logical.py:1: in <module>
    from pyscipopt import Model
../miniforge3/lib/python3.10/site-packages/pyscipopt/__init__.py:11: in <module>
    from pyscipopt.scip      import Model
E   ImportError: libtbb.so.12: cannot open shared object file: No such file or directory
___________________________________________ ERROR collecting tests/test_lp.py ____________________________________________
ImportError while importing test module '/home/ubuntu/PySCIPOpt/tests/test_lp.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../miniforge3/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_lp.py:1: in <module>
    from pyscipopt import LP
../miniforge3/lib/python3.10/site-packages/pyscipopt/__init__.py:11: in <module>
    from pyscipopt.scip      import Model
E   ImportError: libtbb.so.12: cannot open shared object file: No such file or directory
_________________________________________ ERROR collecting tests/test_memory.py __________________________________________
ImportError while importing test module '/home/ubuntu/PySCIPOpt/tests/test_memory.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../miniforge3/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_memory.py:2: in <module>
    from pyscipopt.scip import Model, is_memory_freed
../miniforge3/lib/python3.10/site-packages/pyscipopt/__init__.py:11: in <module>
    from pyscipopt.scip      import Model
E   ImportError: libtbb.so.12: cannot open shared object file: No such file or directory
__________________________________________ ERROR collecting tests/test_model.py __________________________________________
ImportError while importing test module '/home/ubuntu/PySCIPOpt/tests/test_model.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../miniforge3/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_model.py:3: in <module>
    from pyscipopt import Model
../miniforge3/lib/python3.10/site-packages/pyscipopt/__init__.py:11: in <module>
    from pyscipopt.scip      import Model
E   ImportError: libtbb.so.12: cannot open shared object file: No such file or directory
__________________________________________ ERROR collecting tests/test_nlrow.py __________________________________________
ImportError while importing test module '/home/ubuntu/PySCIPOpt/tests/test_nlrow.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../miniforge3/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_nlrow.py:3: in <module>
    from pyscipopt import Model, Heur, SCIP_RESULT, quicksum, SCIP_PARAMSETTING, SCIP_HEURTIMING
../miniforge3/lib/python3.10/site-packages/pyscipopt/__init__.py:11: in <module>
    from pyscipopt.scip      import Model
E   ImportError: libtbb.so.12: cannot open shared object file: No such file or directory
_________________________________________ ERROR collecting tests/test_nodesel.py _________________________________________
ImportError while importing test module '/home/ubuntu/PySCIPOpt/tests/test_nodesel.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../miniforge3/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_nodesel.py:1: in <module>
    from pyscipopt import Model
../miniforge3/lib/python3.10/site-packages/pyscipopt/__init__.py:11: in <module>
    from pyscipopt.scip      import Model
E   ImportError: libtbb.so.12: cannot open shared object file: No such file or directory
________________________________________ ERROR collecting tests/test_nonlinear.py ________________________________________
ImportError while importing test module '/home/ubuntu/PySCIPOpt/tests/test_nonlinear.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../miniforge3/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_nonlinear.py:3: in <module>
    from pyscipopt import Model, quicksum, sqrt
../miniforge3/lib/python3.10/site-packages/pyscipopt/__init__.py:11: in <module>
    from pyscipopt.scip      import Model
E   ImportError: libtbb.so.12: cannot open shared object file: No such file or directory
_________________________________________ ERROR collecting tests/test_pricer.py __________________________________________
ImportError while importing test module '/home/ubuntu/PySCIPOpt/tests/test_pricer.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../miniforge3/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_pricer.py:2: in <module>
    from pyscipopt import Model, Pricer, SCIP_RESULT, SCIP_PARAMSETTING, quicksum
../miniforge3/lib/python3.10/site-packages/pyscipopt/__init__.py:11: in <module>
    from pyscipopt.scip      import Model
E   ImportError: libtbb.so.12: cannot open shared object file: No such file or directory
________________________________________ ERROR collecting tests/test_quadcons.py _________________________________________
ImportError while importing test module '/home/ubuntu/PySCIPOpt/tests/test_quadcons.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../miniforge3/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_quadcons.py:1: in <module>
    from pyscipopt import Model
../miniforge3/lib/python3.10/site-packages/pyscipopt/__init__.py:11: in <module>
    from pyscipopt.scip      import Model
E   ImportError: libtbb.so.12: cannot open shared object file: No such file or directory
________________________________________ ERROR collecting tests/test_quickprod.py ________________________________________
ImportError while importing test module '/home/ubuntu/PySCIPOpt/tests/test_quickprod.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../miniforge3/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_quickprod.py:1: in <module>
    from pyscipopt import Model, quickprod
../miniforge3/lib/python3.10/site-packages/pyscipopt/__init__.py:11: in <module>
    from pyscipopt.scip      import Model
E   ImportError: libtbb.so.12: cannot open shared object file: No such file or directory
________________________________________ ERROR collecting tests/test_quicksum.py _________________________________________
ImportError while importing test module '/home/ubuntu/PySCIPOpt/tests/test_quicksum.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../miniforge3/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_quicksum.py:1: in <module>
    from pyscipopt import Model, quicksum
../miniforge3/lib/python3.10/site-packages/pyscipopt/__init__.py:11: in <module>
    from pyscipopt.scip      import Model
E   ImportError: libtbb.so.12: cannot open shared object file: No such file or directory
_________________________________________ ERROR collecting tests/test_reader.py __________________________________________
ImportError while importing test module '/home/ubuntu/PySCIPOpt/tests/test_reader.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../miniforge3/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_reader.py:4: in <module>
    from pyscipopt import Model, quicksum, Reader, SCIP_RESULT
../miniforge3/lib/python3.10/site-packages/pyscipopt/__init__.py:11: in <module>
    from pyscipopt.scip      import Model
E   ImportError: libtbb.so.12: cannot open shared object file: No such file or directory
__________________________________________ ERROR collecting tests/test_relax.py __________________________________________
ImportError while importing test module '/home/ubuntu/PySCIPOpt/tests/test_relax.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../miniforge3/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_relax.py:1: in <module>
    from pyscipopt import Model
../miniforge3/lib/python3.10/site-packages/pyscipopt/__init__.py:11: in <module>
    from pyscipopt.scip      import Model
E   ImportError: libtbb.so.12: cannot open shared object file: No such file or directory
__________________________________________ ERROR collecting tests/test_reopt.py __________________________________________
ImportError while importing test module '/home/ubuntu/PySCIPOpt/tests/test_reopt.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../miniforge3/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_reopt.py:2: in <module>
    from pyscipopt import Model
../miniforge3/lib/python3.10/site-packages/pyscipopt/__init__.py:11: in <module>
    from pyscipopt.scip      import Model
E   ImportError: libtbb.so.12: cannot open shared object file: No such file or directory
__________________________________________ ERROR collecting tests/test_short.py __________________________________________
ImportError while importing test module '/home/ubuntu/PySCIPOpt/tests/test_short.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../miniforge3/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_short.py:1: in <module>
    from pyscipopt import Model
../miniforge3/lib/python3.10/site-packages/pyscipopt/__init__.py:11: in <module>
    from pyscipopt.scip      import Model
E   ImportError: libtbb.so.12: cannot open shared object file: No such file or directory
________________________________________ ERROR collecting tests/test_solution.py _________________________________________
ImportError while importing test module '/home/ubuntu/PySCIPOpt/tests/test_solution.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../miniforge3/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_solution.py:1: in <module>
    from pyscipopt import Model
../miniforge3/lib/python3.10/site-packages/pyscipopt/__init__.py:11: in <module>
    from pyscipopt.scip      import Model
E   ImportError: libtbb.so.12: cannot open shared object file: No such file or directory
__________________________________________ ERROR collecting tests/test_tree.py ___________________________________________
ImportError while importing test module '/home/ubuntu/PySCIPOpt/tests/test_tree.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../miniforge3/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_tree.py:3: in <module>
    from pyscipopt import Model, Eventhdlr, SCIP_RESULT, SCIP_EVENTTYPE, SCIP_PARAMSETTING
../miniforge3/lib/python3.10/site-packages/pyscipopt/__init__.py:11: in <module>
    from pyscipopt.scip      import Model
E   ImportError: libtbb.so.12: cannot open shared object file: No such file or directory
___________________________________________ ERROR collecting tests/test_tsp.py ___________________________________________
ImportError while importing test module '/home/ubuntu/PySCIPOpt/tests/test_tsp.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../miniforge3/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_tsp.py:1: in <module>
    from pyscipopt import Model, Conshdlr, quicksum, SCIP_RESULT
../miniforge3/lib/python3.10/site-packages/pyscipopt/__init__.py:11: in <module>
    from pyscipopt.scip      import Model
E   ImportError: libtbb.so.12: cannot open shared object file: No such file or directory
__________________________________________ ERROR collecting tests/test_vars.py ___________________________________________
ImportError while importing test module '/home/ubuntu/PySCIPOpt/tests/test_vars.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../miniforge3/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_vars.py:1: in <module>
    from pyscipopt import Model
../miniforge3/lib/python3.10/site-packages/pyscipopt/__init__.py:11: in <module>
    from pyscipopt.scip      import Model
E   ImportError: libtbb.so.12: cannot open shared object file: No such file or directory
================================================ short test summary info =================================================
ERROR tests/test_benders.py
ERROR tests/test_branch_probing_lp.py
ERROR tests/test_conshdlr.py
ERROR tests/test_copy.py
ERROR tests/test_customizedbenders.py
ERROR tests/test_cutsel.py
ERROR tests/test_event.py
ERROR tests/test_expr.py
ERROR tests/test_gomory.py
ERROR tests/test_heur.py
ERROR tests/test_knapsack.py
ERROR tests/test_linexpr.py
ERROR tests/test_logical.py
ERROR tests/test_lp.py
ERROR tests/test_memory.py
ERROR tests/test_model.py
ERROR tests/test_nlrow.py
ERROR tests/test_nodesel.py
ERROR tests/test_nonlinear.py
ERROR tests/test_pricer.py
ERROR tests/test_quadcons.py
ERROR tests/test_quickprod.py
ERROR tests/test_quicksum.py
ERROR tests/test_reader.py
ERROR tests/test_relax.py
ERROR tests/test_reopt.py
ERROR tests/test_short.py
ERROR tests/test_solution.py
ERROR tests/test_tree.py
ERROR tests/test_tsp.py
ERROR tests/test_vars.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 31 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================= 1 skipped, 31 errors in 2.76s ==============================================
`

Seems to be the same libtbb error.

**Comment by Joao-Dionisio** [comment]
I am sorry to hear that @DigitalGabriele. 

I found this [question] on StackExchange. Apparently, it's PaPILO, the parallel presolver, that requires TBB. Have you installed TBB? Is everything working correctly?

Alternatively, you can also try building SCIP with PaPILO disabled, but maybe try out the first option.

**Comment by DigitalGabriele** [comment]
I don't see the link for Stackexchange. 

I tried installing TBB by running both of these lines: `sudo apt-get install libtbb2 or conga install tbb=2020.2 `

But nothing worked.

**Comment by DigitalGabriele** [comment]
```(base) ubuntu@ubuntu-desktop:~$ sudo apt-get install libtbb-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libtbb-dev is already the newest version (2017~U7-8).
```

**Comment by Joao-Dionisio** [comment]
Hmmm it mentions that the newest version is ```2017-U7-8```, but in the Stack Exchange, it says that 

> Unfortunately, PaPILO requires TBB2020 and can not handle TBB2021 (at least for the current version 1.x).

Maybe it's because you're installing ```libtbb-dev```? Do you know if you can install regular TBB2020?

I'm going to convert this issue into a conversation, to avoid flooding the repo.

**Comment by DigitalGabriele** [comment]
Ok, I ran the following line to figure out if I even have this libtbb12. 

```
(base) ubuntu@ubuntu-desktop:~$ sudo find / -name libtbb.so.12
[sudo] password for ubuntu: 
/home/ubuntu/scipoptsuite-8.0.4/build/_deps/tbb-build/gnu_7.5_cxx11_64_relwithdebinfo/libtbb.so.12
/home/ubuntu/scipoptsuite-8.0.4/build/_deps/local/lib/libtbb.so.12
find: ‘/run/user/121/gvfs’: Permission denied
/usr/local/lib/cmake/papilo/_deps/tbb-build/gnu_7.5_cxx11_64_relwithdebinfo/libtbb.so.12
/usr/local/lib/cmake/papilo/_deps/local/lib/libtbb.so.12

```

I guess I do have it? How do I point to it? Is this a correct way?

`export LD_LIBRARY_PATH=/home/ubuntu/scipoptsuite-8.0.4/build/_deps/local/lib/libtbb.so.12:${LD_LIBRARY_PATH}`

**Comment by Joao-Dionisio** [comment]
I have no clue, @DigitalGabriele, this kind of thing is a bit out of my league... But maybe try that out! I don't know if you'll need to build SCIP again, or if you need to say explicitly where to find libtbb during this building process. Let me know how it goes!

**Comment by Joao-Dionisio** [comment]
Very nice, @DigitalGabriele! Thank you as well for providing a well-formatted answer with your solution, now I also know what can be done and others will as well :)

I hope you enjoy PySCIPOpt!

I'll be closing this issue, and keeping the other one open, as it may still be relevant. Cheers!
