### ISSUE TITLE
PySCIPOpt evidently installs SCIP 8.1 but looks for 8.0

### ISSUE THREAD

**Issue by jwarley** [scipopt/PySCIPOpt#762]
**Describe the bug**
Importing PySCIPOpt fails due to missing `libscip.8.0.dylib`, which seems to be because conda installs SCIP 8.1 instead.

**To Reproduce**
```conda install -c conda-forge pyscipopt```

(username and env replaced by --)

```
>>> from pyscipopt.scip import Model
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/--/opt/anaconda3/envs/--/lib/python3.9/site-packages/pyscipopt/__init__.py", line 11, in <module>
    from pyscipopt.scip      import Model
ImportError: dlopen(/Users/--/opt/anaconda3/envs/--/lib/python3.9/site-packages/pyscipopt/scip.cpython-39-darwin.so, 0x0002): Library not loaded: @rpath/libscip.8.0.dylib
  Referenced from: <5DE2CACD-8B79-34D6-894E-64ED96427945> /Users/--/opt/anaconda3/envs/--/lib/python3.9/site-packages/pyscipopt/scip.cpython-39-darwin.so
  Reason: tried: '/usr/local/lib/libscip.8.0.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/lib/libscip.8.0.dylib' (no such file), '/Users/--/opt/anaconda3/envs/--/lib/python3.9/site-packages/pyscipopt/../../../libscip.8.0.dylib' (no such file), '/usr/local/lib/libscip.8.0.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/lib/libscip.8.0.dylib' (no such file), '/Users/--/opt/anaconda3/envs/--/lib/python3.9/site-packages/pyscipopt/../../../libscip.8.0.dylib' (no such file), '/Users/--/opt/anaconda3/envs/--/lib/libscip.8.0.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/--/opt/anaconda3/envs/--/lib/libscip.8.0.dylib' (no such file), '/Users/--/opt/anaconda3/envs/--/bin/../lib/libscip.8.0.dylib' (no such file), '/Users/--/opt/anaconda3/envs/--/lib/libscip.8.0.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/--/opt/anaconda3/envs/--/lib/libscip.8.0.dylib' (no such file), '/Users/--/opt/anaconda3/envs/--/bin/../lib/libscip.8.0.dylib' (no such file), '/usr/local/lib/libscip.8.0.dylib' (no such file), '/usr/lib/libscip.8.0.dylib' (no such file, not in dyld cache)
```

And indeed, 8.0 is not present but 8.1 is:

```
exa /Users/--/opt/anaconda3/envs/--/lib | rg scip
libscip.8.1.0.0.dylib
libscip.8.1.dylib -> libscip.8.1.0.0.dylib
libscip.dylib -> libscip.8.1.0.0.dylib
```

**Expected behavior**
For conda to install the appropriate version of SCIP.

**System**
 - OS: Mac OS 14.1.1
 - Version 4.3.0
 - SCIP version 8.1.0
 - How did you install `pyscipopt`? (recommended conda command, described above)

**Comment by Joao-Dionisio** [comment]
Hello, @jwarley, thank you for your issue! We learned about this a couple of days ago, we're working on fixing it.

**Comment by mmghannam** [comment]
Should be fixed now! @jwarley feel free to reopen if you still have an issue.
